import { readdirSync, readFileSync } from "node:fs";
import { join } from "node:path";
import { getConstructionPlans, getMigrationPlans, getRollbackPlans } from "pg-boss";
import pgBossPackage from "pg-boss/package.json";
import { MIGRATIONS_DIR } from "../database/migrate-cli";
import { JOB_QUEUE_SCHEMA } from "./job-queue-schema";

/**
 * The pg-boss schema is created and upgraded by the project migrations
 * (ARCHITECTURE 4.12 I112), never by pg-boss itself at start-up
 * (`migrate: false`). A migration that changes it carries the marker
 * `-- pg-boss schema version: <n>`; the last marker is the version the
 * migrations produce. The SQL is pg-boss's own (`getConstructionPlans`,
 * `getMigrationPlans`, `getRollbackPlans`), without its `BEGIN`/`COMMIT`:
 * the migration tool runs every migration in a transaction of its own.
 * For scripts and tests only (it needs the migration tool).
 */

const MARKER = /^-- pg-boss schema version: (\d+)$/m;

/** The schema version the installed pg-boss requires. */
export function installedJobQueueSchemaVersion(): number {
  return pgBossPackage.pgboss.schema;
}

/** The schema version the migrations produce (null — no migration creates it). */
export function migratedJobQueueSchemaVersion(dir = MIGRATIONS_DIR): number | null {
  let version: number | null = null;
  for (const file of readdirSync(dir)
    .filter((name) => name.endsWith(".sql"))
    .sort()) {
    const match = MARKER.exec(readFileSync(join(dir, file), "utf8"));
    if (match) {
      version = Number(match[1]);
    }
  }
  return version;
}

function withoutTransaction(plan: string): string {
  const lines = plan.split("\n");
  const kept = lines.filter((line) => !/^\s*(BEGIN|COMMIT);\s*$/.test(line));
  if (lines.length - kept.length < 2) {
    throw new Error("Unexpected pg-boss plan: no BEGIN/COMMIT around it");
  }
  return kept
    .map((line) => line.trimEnd())
    .join("\n")
    .trim();
}

/**
 * The migration that brings the schema from `from` (null — not installed)
 * to the version the installed pg-boss requires.
 */
export function jobQueueSchemaMigration(from: number | null): string {
  const to = installedJobQueueSchemaVersion();
  let up: string;
  let down: string;
  let about: string;
  if (from === null) {
    about = `Background job queue (pg-boss ${pgBossPackage.version}, ARCHITECTURE 13.1, 4.12; TASK-008).`;
    up = withoutTransaction(getConstructionPlans(JOB_QUEUE_SCHEMA));
    down = `DROP SCHEMA ${JOB_QUEUE_SCHEMA} CASCADE;`;
  } else {
    about = `Background job queue schema ${String(from)} -> ${String(to)} (pg-boss ${pgBossPackage.version}).`;
    up = withoutTransaction(getMigrationPlans(JOB_QUEUE_SCHEMA, from));
    const rollbacks: string[] = [];
    for (let version = to; version > from; version -= 1) {
      rollbacks.push(withoutTransaction(getRollbackPlans(JOB_QUEUE_SCHEMA, version)));
    }
    down = rollbacks.join("\n\n");
  }
  return [
    "-- Up Migration",
    `-- ${about}`,
    "-- Generated by `pnpm --filter api jobs:schema-migration generate` from",
    "-- pg-boss's own plans; do not edit by hand.",
    `-- pg-boss schema version: ${String(to)}`,
    up,
    "",
    "-- Down Migration",
    down,
    "",
  ].join("\n");
}
