import type { Compatibility, OrderStatusGroup } from "@adclub/ui-core";

/**
 * Labels of the development showcase only (not product texts). The Kazakh
 * column is a layout check, like the Kazakh section of the mockups.
 */
export type ShowcaseLang = "ru" | "kk";

const ru = {
  title: "Витрина компонентов",
  subtitle: "Asia Drive Club · дизайн-система",
  theme: "Оформление",
  themeDark: "Тёмная",
  themeLight: "Светлая",
  themeSystem: "Как в системе",
  language: "Язык подписей",
  cabinet: "Кабинет поставщика",
  admin: "Админка",
  footer: "Витрина доступна только в режиме разработки.",
  sample: "Моторное масло 5W-30, полностью синтетическое, 4 литра — выберите товар",
  sections: {
    brand: "Бренд",
    colors: "Цвета",
    typography: "Типографика",
    icons: "Значки",
    buttons: "Кнопки",
    fields: "Поля ввода",
    choice: "Выбор",
    marks: "Метки",
    feedback: "Сообщения и состояния",
    table: "Таблица",
    code: "Код и QR",
  },
  notes: {
    brand:
      "Логотип следует теме: шампань на графите, графит на светлом. Только AD — при ширине меньше 48.",
    colors: "Токены DESIGN.md 7.2 текущей темы.",
    typography: "Onest 400/500/700; цены и коды — моноширинные цифры.",
    icons: "Tabler Icons, линейные, толщина 1,75.",
    buttons:
      "Нажатие — затемнение, фокус — рамка 2 px. Загрузка не меняет ширину и не даёт нажать повторно (попробуйте двойной клик и Enter).",
    fields: "Подпись сверху, подсказка и ошибка снизу; введённое при ошибке не стирается.",
    choice: "Зона нажатия — не меньше 48 × 48.",
    marks: "Смысл — значком и текстом, не только цветом.",
    feedback: "Всплывающее сообщение — только подтверждения; ошибки — на экране.",
    table: "Строка 48; ячейка ИИ — бирюзовая со значком; резкое изменение — предупреждение.",
    code: "QR всегда чёрный на белом, с тихой зоной; до принятия — 30 % и пояснение.",
  },
  labels: {
    logoAuto: "По теме",
    logoFixed: "Версии и иконка сайта",
    iconButton: "Кнопки-значки (с текстом для программ чтения экрана)",
    size: "Размер",
    states: "Отключённые, загрузка, отмена заявки",
    pressGuard: "Защита от повторного нажатия",
    longLabel: "Длинная подпись",
    chips: "Чипы-фильтры",
    quantity: "Количество",
    status: "Статусы заявки",
    compatibility: "Совместимость",
    ai: "Данные ИИ",
    rating: "Рейтинг",
    aiPilot: "AI Pilot",
    toastAndDialog: "Всплывающее сообщение и диалог",
    skeleton: "Каркас загрузки",
  },
  primary: "Отправить заявку",
  secondary: "Оформить",
  textButton: "Сбросить фильтры",
  danger: "Удалить аккаунт",
  disabled: "Недоступно",
  cancelOrder: "Отменить заявку",
  slowAction: "Действие на 2 секунды",
  controlledLoading: "Загрузка по состоянию",
  stop: "Остановить",
  pressCount: "Срабатываний",
  longButton: "Подтвердить срок и уведомить покупателя о готовности заказа к выдаче",
  back: "Назад",
  close: "Закрыть",
  search: "Поиск",
  clear: "Очистить",
  searchValue: "масло 5W-30",
  searchPlaceholder: "Товар, артикул или услуга",
  fieldName: "Название компании",
  fieldHint: "Так её увидят покупатели",
  placeholder: "Например, Автомаркет",
  fieldPhone: "Номер телефона",
  fieldError: "Номер должен содержать 10 цифр после +7",
  fieldDisabled: "Город",
  disabledValue: "Алматы",
  recognized: "распознано",
  proposed: "предложено ИИ",
  aiHint: "Проверьте и подтвердите",
  aiConfirmedHint: "Подтверждено",
  confirm: "Подтвердить",
  codeLabel: "Код заявки",
  codeError: "Заявка с таким кодом не найдена",
  erase: "Стереть",
  find: "Найти",
  chips: ["В наличии", "Подходит к моему авто", "Доставка сегодня"],
  sort: "Сортировка",
  segments: ["Рекомендуемые", "Дешевле", "Быстрее"],
  switchLabel: "Уведомления о новых заявках",
  switchDescription: "В приложении и в WhatsApp",
  checkboxLabel: "Цена изменилась больше чем на 30 % — подтверждаю",
  delivery: "Способ получения",
  pickup: "Самовывоз",
  courier: "Доставка",
  courierDescription: "Стоимость согласуется с поставщиком",
  quantity: "Количество",
  decrease: "Уменьшить",
  increase: "Увеличить",
  status: {
    waiting: "Создана",
    needsReply: "Предложен другой срок",
    inProgress: "Принята",
    ready: "Можно забирать",
    finished: "Отменена",
  } satisfies Record<OrderStatusGroup, string>,
  compatibility: {
    fits: "Подходит к Geely Monjaro",
    missingParameter: "Уточните объём двигателя",
    doesNotFit: "Не подходит к Geely Monjaro",
    unknown: "Совместимость не указана",
  } satisfies Record<Compatibility, string>,
  ratingLabel: "Рейтинг 4,8 из 5, 23 оценки",
  noRating: "Пока нет оценок",
  aiPilotWeb:
    "Персонаж — в мобильном приложении (вкладка AI Pilot); в кабинете центральная кнопка — «Сканер»",
  offline: "Нет сети. Показаны данные, сохранённые ранее.",
  update: "Обновить",
  paymentProblem: "Не удалось списать оплату подписки. Обновите способ оплаты.",
  bannerError: "Файл не загружен: формат не поддерживается.",
  copyCode: "Скопировать код",
  copied: "Код скопирован",
  dialogTitle: "Отменить заявку?",
  dialogText: "Поставщик получит уведомление. Восстановить заявку будет нельзя.",
  keepOrder: "Не отменять",
  loading: "Загрузка",
  emptyTitle: "Заявок пока нет",
  emptyText: "Когда покупатель оформит заявку, она появится здесь.",
  resetFilters: "Сбросить фильтры",
  errorTitle: "Не удалось загрузить",
  errorText: "Проверьте связь и попробуйте ещё раз.",
  retry: "Повторить",
  table: {
    name: "Позиция",
    article: "Артикул",
    auto: "определено автоматически",
    price: "Цена",
    stock: "Остаток",
    pads: "Колодки тормозные передние",
    filter: "Фильтр масляный",
    edit: "Изменить",
  },
  codeTitle: "Код для получения",
  qrLabel: "QR-код заявки",
  codePending: "Код появится, когда поставщик примет заявку",
  nav: {
    label: "Разделы",
    orders: "Заявки",
    newOrders: "3 новые",
    offers: "Предложения",
    scan: "Сканер",
    price: "Прайс",
    more: "Ещё",
    settings: "Мои настройки",
    moderation: "Модерация",
    catalog: "Справочник",
    admins: "Администраторы",
  },
};

export type ShowcaseTexts = typeof ru;

const kk: ShowcaseTexts = {
  title: "Компоненттер витринасы",
  subtitle: "Asia Drive Club · дизайн-жүйе",
  theme: "Безендіру",
  themeDark: "Қараңғы",
  themeLight: "Ашық",
  themeSystem: "Жүйедегідей",
  language: "Жазулар тілі",
  cabinet: "Жеткізуші кабинеті",
  admin: "Әкімші панелі",
  footer: "Витрина тек әзірлеу режимінде қолжетімді.",
  sample: "Қозғалтқыш майы 5W-30, толық синтетикалық, 4 литр — Өнімді таңдаңыз",
  sections: {
    brand: "Бренд",
    colors: "Түстер",
    typography: "Типографика",
    icons: "Белгішелер",
    buttons: "Түймелер",
    fields: "Енгізу өрістері",
    choice: "Таңдау",
    marks: "Белгілер",
    feedback: "Хабарламалар мен күйлер",
    table: "Кесте",
    code: "Код және QR",
  },
  notes: {
    brand:
      "Логотип тақырыпқа сәйкес: графитте шампань, ашық фонда графит. Ені 48-ден аз болса — тек AD.",
    colors: "Ағымдағы тақырыптың DESIGN.md 7.2 токендері.",
    typography: "Onest 400/500/700; бағалар мен кодтар — бірдей енді цифрлар.",
    icons: "Tabler Icons, сызықтық, қалыңдығы 1,75.",
    buttons:
      "Басу — күңгірттеу, фокус — 2 px жиектеме. Жүктелу енін өзгертпейді және қайта басуға жол бермейді (екі рет басып, Enter пернесін байқап көріңіз).",
    fields: "Жазу жоғарыда, кеңес пен қате төменде; қате кезінде енгізілгені өшірілмейді.",
    choice: "Басу аймағы — кемінде 48 × 48.",
    marks: "Мағына тек түспен емес, белгіше және мәтінмен беріледі.",
    feedback: "Қалқымалы хабар — тек растаулар үшін; қателер — экранның өзінде.",
    table: "Жол биіктігі 48; ЖИ ұяшығы — белгішесі бар көгілдір; күрт өзгеріс — ескерту.",
    code: "QR әрқашан ақ фондағы қара, тыныш аймағымен; қабылданғанға дейін — 30 % және түсініктеме.",
  },
  labels: {
    logoAuto: "Тақырып бойынша",
    logoFixed: "Нұсқалар және сайт белгішесі",
    iconButton: "Белгіше-түймелер (экран оқу бағдарламаларына арналған мәтінмен)",
    size: "Өлшемі",
    states: "Өшірулі, жүктелу, өтінімді болдырмау",
    pressGuard: "Қайта басудан қорғау",
    longLabel: "Ұзын жазу",
    chips: "Сүзгі-чиптер",
    quantity: "Саны",
    status: "Өтінім мәртебелері",
    compatibility: "Үйлесімділік",
    ai: "ЖИ деректері",
    rating: "Рейтинг",
    aiPilot: "AI Pilot",
    toastAndDialog: "Қалқымалы хабар және диалог",
    skeleton: "Жүктелу қаңқасы",
  },
  primary: "Өтінім жіберу",
  secondary: "Рәсімдеу",
  textButton: "Сүзгілерді тазалау",
  danger: "Аккаунтты жою",
  disabled: "Қолжетімсіз",
  cancelOrder: "Өтінімнен бас тарту",
  slowAction: "2 секундтық әрекет",
  controlledLoading: "Күй бойынша жүктелу",
  stop: "Тоқтату",
  pressCount: "Іске қосылу саны",
  longButton: "Мерзімді растап, сатып алушыға тапсырыстың беруге дайын екенін хабарлау",
  back: "Артқа",
  close: "Жабу",
  search: "Іздеу",
  clear: "Тазалау",
  searchValue: "май 5W-30",
  searchPlaceholder: "Тауар, артикул немесе қызмет",
  fieldName: "Компания атауы",
  fieldHint: "Сатып алушылар оны осылай көреді",
  placeholder: "Мысалы, Автомаркет",
  fieldPhone: "Телефон нөмірі",
  fieldError: "Нөмірде +7-ден кейін 10 цифр болуы керек",
  fieldDisabled: "Қала",
  disabledValue: "Алматы",
  recognized: "танылды",
  proposed: "ЖИ ұсынды",
  aiHint: "Тексеріп, растаңыз",
  aiConfirmedHint: "Расталды",
  confirm: "Растау",
  codeLabel: "Өтінім коды",
  codeError: "Мұндай кодпен өтінім табылмады",
  erase: "Өшіру",
  find: "Табу",
  chips: ["Қоймада бар", "Менің көлігіме сәйкес", "Бүгін жеткізу"],
  sort: "Сұрыптау",
  segments: ["Ұсынылатын", "Арзанырақ", "Жылдамырақ"],
  switchLabel: "Жаңа өтінімдер туралы хабарламалар",
  switchDescription: "Қосымшада және WhatsApp-та",
  checkboxLabel: "Баға 30 %-дан астам өзгерді — растаймын",
  delivery: "Алу тәсілі",
  pickup: "Өзі алып кету",
  courier: "Жеткізу",
  courierDescription: "Құны жеткізушімен келісіледі",
  quantity: "Саны",
  decrease: "Азайту",
  increase: "Көбейту",
  status: {
    waiting: "Құрылды",
    needsReply: "Басқа мерзім ұсынылды",
    inProgress: "Қабылданды",
    ready: "Алып кетуге болады",
    finished: "Болдырылмады",
  },
  compatibility: {
    fits: "Geely Monjaro көлігіне сәйкес келеді",
    missingParameter: "Қозғалтқыш көлемін нақтылаңыз",
    doesNotFit: "Geely Monjaro көлігіне сәйкес келмейді",
    unknown: "Үйлесімділігі көрсетілмеген",
  },
  ratingLabel: "Рейтинг 5-тен 4,8, 23 баға",
  noRating: "Әзірге бағалар жоқ",
  aiPilotWeb:
    "Кейіпкер — мобильді қосымшада (AI Pilot қойындысы); кабинетте ортадағы түйме — «Сканер»",
  offline: "Желі жоқ. Бұрын сақталған деректер көрсетілген.",
  update: "Жаңарту",
  paymentProblem: "Жазылым төлемін есептен шығару мүмкін болмады. Төлем тәсілін жаңартыңыз.",
  bannerError: "Файл жүктелмеді: пішімі қолдау көрсетілмейді.",
  copyCode: "Кодты көшіру",
  copied: "Код көшірілді",
  dialogTitle: "Өтінімнен бас тартасыз ба?",
  dialogText: "Жеткізушіге хабарлама жіберіледі. Өтінімді қалпына келтіру мүмкін болмайды.",
  keepOrder: "Бас тартпау",
  loading: "Жүктелуде",
  emptyTitle: "Әзірге өтінімдер жоқ",
  emptyText: "Сатып алушы өтінім рәсімдегенде, ол осында пайда болады.",
  resetFilters: "Сүзгілерді тазалау",
  errorTitle: "Жүктеу мүмкін болмады",
  errorText: "Байланысты тексеріп, қайталап көріңіз.",
  retry: "Қайталау",
  table: {
    name: "Позиция",
    article: "Артикул",
    auto: "автоматты түрде анықталды",
    price: "Бағасы",
    stock: "Қалдығы",
    pads: "Алдыңғы тежегіш қалыптары",
    filter: "Май сүзгісі",
    edit: "Өзгерту",
  },
  codeTitle: "Алуға арналған код",
  qrLabel: "Өтінімнің QR-коды",
  codePending: "Жеткізуші өтінімді қабылдағанда код пайда болады",
  nav: {
    label: "Бөлімдер",
    orders: "Өтінімдер",
    newOrders: "3 жаңа",
    offers: "Ұсыныстар",
    scan: "Сканер",
    price: "Прайс",
    more: "Тағы",
    settings: "Баптауларым",
    moderation: "Модерация",
    catalog: "Анықтамалық",
    admins: "Әкімшілер",
  },
};

export const showcaseTexts: Record<ShowcaseLang, ShowcaseTexts> = { ru, kk };
