// Builds the client brand assets from the approved SVGs in design/brand
// (TASK-075, ARCHITECTURE 4.10): raster icons and splash for the mobile app,
// favicons for the web clients and the SVG module of @adclub/ui-core.
//
//   pnpm brand:assets          write every asset
//   pnpm brand:assets --check  exit 1 if any asset differs from what would be written
//
// The SVG sources themselves are produced by design/brand/build.py and
// design/brand/assistant.py and are never edited here.
import { readFile, writeFile, mkdir } from "node:fs/promises";
import { dirname, join, relative } from "node:path";
import { fileURLToPath } from "node:url";
import { Resvg } from "@resvg/resvg-js";
import * as prettier from "prettier";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const brand = join(root, "design", "brand");
const check = process.argv.includes("--check");

const AI_PILOT_STATES = ["idle", "listening", "thinking", "happy", "unsure"];
const AI_PILOT_COLORWAYS = ["on-champagne", "on-graphite"];
const BRAND_SVGS = [
  "logo-champagne",
  "logo-graphite",
  "logo-white",
  "mark-ad-champagne",
  "mark-ad-graphite",
  "mark-ad-white",
  "favicon",
];

/** Raster outputs: source SVG in design/brand, target, pixel width. */
const RASTERS = [
  // iOS and store icon: opaque 1024 square, the system applies the mask.
  ["app-icon.svg", "apps/mobile/assets/icon.png", 1024],
  // Android adaptive icon layers (108 dp canvas) and themed icon (Android 13+).
  ["android-icon-background.svg", "apps/mobile/assets/android-icon-background.png", 1024],
  ["android-icon-foreground.svg", "apps/mobile/assets/android-icon-foreground.png", 1024],
  ["android-icon-monochrome.svg", "apps/mobile/assets/android-icon-monochrome.png", 1024],
  // Android notification icon: white AD on transparent, 24 dp at xxxhdpi.
  ["android-notification-icon.svg", "apps/mobile/assets/notification-icon.png", 96],
  // Splash: the champagne lockup; the graphite background comes from app.json.
  ["logo-champagne.svg", "apps/mobile/assets/splash-icon.png", 1024],
  // `expo start --web` favicon.
  ["favicon.svg", "apps/mobile/assets/favicon.png", 48],
  // Web clients: home screen icon (iOS ignores SVG there).
  ["app-icon.svg", "apps/supplier-web/public/apple-touch-icon.png", 180],
  ["app-icon.svg", "apps/admin-web/public/apple-touch-icon.png", 180],
];

/** Files copied verbatim. */
const COPIES = [
  ["favicon.svg", "apps/supplier-web/public/favicon.svg"],
  ["favicon.svg", "apps/admin-web/public/favicon.svg"],
];

const readSvg = (name) => readFile(join(brand, name), "utf8");

function render(svg, width) {
  return new Resvg(svg, { fitTo: { mode: "width", value: width } }).render().asPng();
}

async function svgModule() {
  const brandEntries = await Promise.all(
    BRAND_SVGS.map(async (name) => [name, (await readSvg(`${name}.svg`)).trim()]),
  );
  const pilotEntries = await Promise.all(
    AI_PILOT_STATES.map(async (state) => [
      state,
      Object.fromEntries(
        await Promise.all(
          AI_PILOT_COLORWAYS.map(async (colorway) => [
            colorway,
            (await readSvg(`assistant/ai-pilot-${state}-${colorway}.svg`)).trim(),
          ]),
        ),
      ),
    ]),
  );
  const source = `// Generated by \`pnpm brand:assets\` from design/brand — do not edit.
import type { AiPilotColorway, AiPilotState } from "../logic";

export const brandSvg = ${JSON.stringify(Object.fromEntries(brandEntries), null, 2)} as const;

export type BrandSvgName = keyof typeof brandSvg;

export const aiPilotSvg: Record<AiPilotState, Record<AiPilotColorway, string>> = ${JSON.stringify(
    Object.fromEntries(pilotEntries),
    null,
    2,
  )};
`;
  const target = join(root, "packages/ui-core/src/brand/brand-svg.ts");
  const options = (await prettier.resolveConfig(target)) ?? {};
  return prettier.format(source, { ...options, filepath: target });
}

async function outputs() {
  const list = [];
  for (const [source, target, width] of RASTERS) {
    list.push([target, render(await readSvg(source), width)]);
  }
  for (const [source, target] of COPIES) {
    list.push([target, Buffer.from(await readSvg(source), "utf8")]);
  }
  list.push(["packages/ui-core/src/brand/brand-svg.ts", Buffer.from(await svgModule(), "utf8")]);
  return list;
}

const stale = [];
for (const [target, content] of await outputs()) {
  const path = join(root, target);
  const current = await readFile(path).catch(() => null);
  if (current?.equals(content)) continue;
  if (check) {
    stale.push(relative(root, path));
    continue;
  }
  await mkdir(dirname(path), { recursive: true });
  await writeFile(path, content);
  console.log("wrote", target);
}

if (check && stale.length > 0) {
  console.error(
    `Brand assets are out of date (run \`pnpm brand:assets\`):\n  ${stale.join("\n  ")}`,
  );
  process.exit(1);
}
if (check) console.log("Brand assets are up to date.");
