// Builds the icon path modules from design/icons (TASK-030.A, D-067,
// ARCHITECTURE 4.43): the glyph of every semantic icon for both platforms,
// the glyphs of the catalog's category codes for the app, and the glyphs
// only the development showcase draws.
//
//   pnpm icons                      write the modules
//   pnpm icons --check              exit 1 if a module differs from what would be written
//   pnpm icons --vendor <assets>    copy the Phosphor SVGs the map needs from the
//                                   `assets` folder of @phosphor-icons/core
//                                   (npm pack @phosphor-icons/core), then write
//
// Only the glyphs the map names are vendored and generated, so a bundle never
// carries an icon nobody draws. The SVG sources are the source of truth; the
// modules are never edited by hand.
import { copyFile, mkdir, readdir, readFile, rm, writeFile } from "node:fs/promises";
import { dirname, join, relative } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";
import * as prettier from "prettier";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const iconsDir = join(root, "design", "icons");
const phosphorDir = join(iconsDir, "phosphor");
const customDir = join(iconsDir, "custom");
const args = process.argv.slice(2);
const check = args.includes("--check");
const vendorIndex = args.indexOf("--vendor");
const vendorFrom = vendorIndex >= 0 ? args[vendorIndex + 1] : null;

const map = await import(pathToFileURL(join(iconsDir, "icons.mjs")).href);

/**
 * Phosphor weights we vendor, by the folder (and file suffix) of the package.
 * Light on every size, 16 included (D-067, 04.10.2026): no Regular.
 */
const WEIGHTS = ["light", "fill"];

/** Every Phosphor glyph the map needs, by weight. */
function needed() {
  const phosphor = (name) => !name.startsWith("custom:");
  const light = new Set(
    [...Object.values(map.ui), ...Object.values(map.category), ...map.preview.carCandidates].filter(
      phosphor,
    ),
  );
  return {
    light,
    fill: new Set(Object.values(map.uiFilled)),
  };
}

async function vendor(from) {
  const sets = needed();
  for (const weight of WEIGHTS) {
    const dir = join(phosphorDir, weight);
    await rm(dir, { recursive: true, force: true });
    await mkdir(dir, { recursive: true });
    for (const name of [...sets[weight]].sort()) {
      const file = `${name}-${weight}.svg`;
      await copyFile(join(from, weight, file), join(dir, `${name}.svg`));
    }
  }
  await copyFile(join(from, "..", "LICENSE"), join(phosphorDir, "LICENSE"));
}

/** `<path d>` of a Phosphor file: filled outlines, one or more. */
function phosphorPaths(svg, source) {
  const paths = [...svg.matchAll(/<path d="([^"]+)"\s*\/>/g)].map((match) => ({ d: match[1] }));
  const elements = svg.match(/<(?!svg|\/svg)[a-z]+/g) ?? [];
  if (paths.length === 0 || elements.length !== paths.length) {
    throw new Error(`${source}: expected only <path d="…"/> elements`);
  }
  return paths;
}

/** Our own drawings: strokes of the Light weight (12 on the 256 grid), paths and circles. */
function customPaths(svg, source) {
  if (!/stroke-width="12"/.test(svg)) {
    throw new Error(`${source}: a custom glyph is drawn with stroke-width 12 (Phosphor Light)`);
  }
  const parts = [];
  for (const [element] of svg.matchAll(/<(path|circle)\b[^>]*\/>/g)) {
    if (element.startsWith("<path")) {
      parts.push({ d: element.match(/\bd="([^"]+)"/)[1], stroke: true });
    } else {
      const [cx, cy, r] = ["cx", "cy", "r"].map((attribute) =>
        Number(element.match(new RegExp(`\\b${attribute}="([^"]+)"`))[1]),
      );
      parts.push({
        d: `M${cx - r},${cy}a${r},${r} 0 1 0 ${2 * r},0a${r},${r} 0 1 0 ${-2 * r},0`,
        stroke: true,
      });
    }
  }
  const elements = svg.match(/<(?!svg|\/svg)[a-z]+/g) ?? [];
  if (parts.length === 0 || elements.length !== parts.length) {
    throw new Error(`${source}: expected only <path> and <circle> elements`);
  }
  return parts;
}

async function glyph(name, weight = "light") {
  if (name.startsWith("custom:")) {
    const file = join(customDir, `${name.slice("custom:".length)}.svg`);
    return customPaths(await readFile(file, "utf8"), relative(root, file));
  }
  const file = join(phosphorDir, weight, `${name}.svg`);
  return phosphorPaths(await readFile(file, "utf8"), relative(root, file));
}

const literal = (parts) =>
  `[${parts.map((part) => `{ d: ${JSON.stringify(part.d)}${part.stroke ? ", stroke: true" : ""} }`).join(", ")}]`;

async function record(entries, weight) {
  const lines = [];
  for (const [key, name] of Object.entries(entries)) {
    lines.push(`  ${JSON.stringify(key)}: ${literal(await glyph(name, weight))},`);
  }
  return `{\n${lines.join("\n")}\n}`;
}

const HEADER =
  "// Generated by `pnpm icons` from design/icons (TASK-030.A) — do not edit by hand.\n";

async function modules() {
  const customCategory = Object.entries(map.category)
    .filter(([, name]) => name.startsWith("custom:"))
    .map(([code]) => code);
  const candidates = Object.fromEntries(map.preview.carCandidates.map((name) => [name, name]));
  return {
    "packages/ui-core/src/icons/glyphs.ts": `${HEADER}import type { IconName } from "../logic";
import type { Glyph } from "./glyph";

/** Phosphor Light glyph of every semantic icon (design/icons/icons.mjs, \`ui\`). */
export const uiGlyphs: Record<IconName, Glyph> = ${await record(map.ui)};

/** The filled form of the icons that have one (Phosphor Fill). */
export const uiFilledGlyphs: Partial<Record<IconName, Glyph>> = ${await record(map.uiFilled, "fill")};
`,
    "apps/mobile/src/design-system/category-glyphs.ts": `${HEADER}import type { CategoryIcon } from "@adclub/contracts";
import type { Glyph } from "@adclub/ui-core";

/** The glyph of every category code of the contract (design/icons/icons.mjs, \`category\`). */
export const categoryGlyphs: Record<CategoryIcon, Glyph> = ${await record(map.category)};
`,
    "apps/admin-web/src/catalog/category-glyphs.ts": `${HEADER}import type { CategoryIcon } from "@adclub/contracts";
import type { Glyph } from "@adclub/ui-core";

/** The glyph of every category code — the admin panel's preview of the icon a node carries (TASK-035). */
export const categoryGlyphs: Record<CategoryIcon, Glyph> = ${await record(map.category)};
`,
    "apps/mobile/src/dev/preview-glyphs.ts": `${HEADER}import type { CategoryIcon } from "@adclub/contracts";
import type { Glyph } from "@adclub/ui-core";

/** The car glyphs the Product Owner compares (the first is the one in use). */
export const carCandidateGlyphs: Record<string, Glyph> = ${await record(candidates)};


/** Category codes drawn by us in the Light style, for the Product Owner to approve. */
export const customCategoryIcons: readonly CategoryIcon[] = ${JSON.stringify(customCategory)};
`,
  };
}

if (vendorFrom) {
  await vendor(vendorFrom);
}

const prettierConfig = await prettier.resolveConfig(join(root, "package.json"));
let stale = 0;
for (const [path, source] of Object.entries(await modules())) {
  const target = join(root, path);
  const formatted = await prettier.format(source, { ...prettierConfig, filepath: target });
  let current = null;
  try {
    current = await readFile(target, "utf8");
  } catch {
    current = null;
  }
  if (current === formatted) continue;
  if (check) {
    stale += 1;
    console.error(`stale: ${path} (run pnpm icons)`);
    continue;
  }
  await mkdir(dirname(target), { recursive: true });
  await writeFile(target, formatted);
  console.log(`wrote ${path}`);
}

// Every vendored Phosphor file is one the map needs: nothing unused lingers —
// a whole folder of a weight we no longer use included.
const sets = needed();
const folders = (await readdir(phosphorDir, { withFileTypes: true }))
  .filter((entry) => entry.isDirectory())
  .map((entry) => entry.name);
for (const weight of new Set([...WEIGHTS, ...folders])) {
  let files = [];
  try {
    files = await readdir(join(phosphorDir, weight));
  } catch {
    files = [];
  }
  for (const file of files) {
    if (!sets[weight]?.has(file.replace(/\.svg$/, ""))) {
      stale += 1;
      console.error(`unused: design/icons/phosphor/${weight}/${file}`);
    }
  }
}
if (stale > 0) process.exit(1);
