import type { AiPilotState, Compatibility, OrderStatusGroup } from "@adclub/ui-core";

/**
 * Labels of the development showcase only (not product texts). Kazakh is a
 * layout check with long labels, like the Kazakh section of the mockups.
 */
export type ShowcaseLang = "ru" | "kk";

const ru = {
  title: "Витрина",
  theme: "Оформление",
  themeDark: "Тёмная",
  themeLight: "Светлая",
  themeSystem: "Как в системе",
  language: "Язык подписей",
  current: "Сейчас",
  reduceMotion: "Уменьшить движение",
  on: "включено",
  off: "выключено",
  pilotNote:
    "Пять состояний, две расцветки; «Ждёт» моргает раз в 4–6 с (без моргания при «Уменьшить движение»).",
  pilotStates: {
    idle: "Ждёт",
    listening: "Слушает",
    thinking: "Думает",
    happy: "Нашёл",
    unsure: "Не уверен",
  } satisfies Record<AiPilotState, string>,
  pilotLabel: "AI Pilot, помощник",
  sections: {
    colors: "Цвета",
    typography: "Типографика",
    icons: "Значки",
    buttons: "Кнопки",
    fields: "Поля ввода",
    choice: "Выбор",
    marks: "Метки",
    feedback: "Сообщения и состояния",
    list: "Строки списка",
    code: "Код и QR",
    tabs: "Нижние вкладки",
  },
  sample: "Қозғалтқыш майы 5W-30, толық синтетикалық, 4 литр — Өнімді таңдаңыз",
  back: "Назад",
  close: "Закрыть",
  search: "Поиск",
  clear: "Очистить",
  primary: "Отправить заявку",
  secondary: "Оформить",
  cancelOrder: "Отменить заявку",
  textButton: "Сбросить фильтры",
  danger: "Удалить аккаунт",
  disabled: "Недоступно",
  pressGuard: "Повторные нажатия во время действия не срабатывают:",
  slowAction: "Действие на 2 с, нажатий",
  longButton: "Подтвердить срок и уведомить покупателя о готовности заказа к выдаче",
  fieldName: "Как к вам обращаться",
  fieldHint: "Увидит поставщик в заявке",
  placeholder: "Например, Айжан",
  fieldPhone: "Номер телефона",
  fieldError: "Номер должен содержать 10 цифр после +7",
  fieldDisabled: "Город",
  disabledValue: "Астана",
  recognized: "распознано",
  proposed: "предложено ИИ",
  aiHint: "Проверьте и подтвердите",
  aiConfirmedHint: "Подтверждено",
  confirm: "Подтвердить",
  searchValue: "масло 5W-30",
  searchPlaceholder: "Товар, артикул или услуга",
  codeLabel: "Код заявки",
  codeError: "Заявка с таким кодом не найдена",
  erase: "Стереть",
  find: "Найти",
  chips: ["В наличии", "Подходит к моему авто", "Доставка сегодня"],
  sort: "Сортировка",
  segments: ["Рекомендуемые", "Дешевле", "Быстрее"] as [string, string, string],
  switchLabel: "Уведомления о заявках",
  switchDescription: "Статус, готовность к выдаче",
  checkboxLabel: "Согласен с условиями клуба",
  pickup: "Самовывоз",
  courier: "Доставка",
  courierDescription: "Стоимость согласуется с поставщиком",
  quantity: "Количество",
  decrease: "Уменьшить",
  increase: "Увеличить",
  status: {
    waiting: "Создана",
    needsReply: "Предложен другой срок",
    inProgress: "Принята",
    ready: "Можно забирать",
    finished: "Истекла",
  } satisfies Record<OrderStatusGroup, string>,
  compatibility: {
    fits: "Подходит к Geely Monjaro",
    missingParameter: "Уточните объём двигателя",
    doesNotFit: "Не подходит к Geely Monjaro",
    unknown: "Совместимость не указана",
  } satisfies Record<Compatibility, string>,
  ratingLabel: "Рейтинг 4,8 из 5, 23 оценки",
  noRating: "Пока нет оценок",
  offline: "Нет сети. Показаны данные, сохранённые ранее.",
  paymentProblem: "Не удалось продлить подписку. Обновите способ оплаты.",
  bannerError: "Фото не загрузилось. Попробуйте ещё раз.",
  copyCode: "Скопировать код",
  copied: "Код скопирован",
  openSheet: "Открыть шторку",
  loading: "Загрузка",
  emptyTitle: "Заявок пока нет",
  emptyText: "Найдите товар в каталоге и оформите заявку по клубной цене.",
  resetFilters: "Сбросить фильтры",
  errorTitle: "Не удалось загрузить",
  errorText: "Проверьте связь и попробуйте ещё раз.",
  retry: "Повторить",
  codeTitle: "Код для получения",
  qrLabel: "QR-код заявки",
  codePending: "Код появится, когда поставщик примет заявку",
  tabsFour: "Этапы B–C: четыре вкладки без AI Pilot. Внизу экрана — итоговый вид с AI Pilot.",
  sheetTitle: "Способ получения",
  sheetText: "Шторка закрывается смахиванием вниз и по затемнению.",
  apply: "Применить",
  dialogTitle: "Отменить заявку?",
  dialogText: "Поставщик получит уведомление. Восстановить заявку будет нельзя.",
  keepOrder: "Не отменять",
  tabs: { catalog: "Каталог", orders: "Заявки", garage: "Гараж", profile: "Профиль" },
};

export type ShowcaseTexts = typeof ru;

const kk: ShowcaseTexts = {
  title: "Витрина",
  theme: "Безендіру",
  themeDark: "Қараңғы",
  themeLight: "Ашық",
  themeSystem: "Жүйедегідей",
  language: "Жазулар тілі",
  current: "Қазір",
  reduceMotion: "Қозғалысты азайту",
  on: "қосулы",
  off: "өшірулі",
  pilotNote:
    "Бес күй, екі түс нұсқасы; «Күтеді» күйінде 4–6 секунд сайын жыпылықтайды («Қозғалысты азайту» қосулы болса — жыпылықтамайды).",
  pilotStates: {
    idle: "Күтеді",
    listening: "Тыңдап тұр",
    thinking: "Ойланып тұр",
    happy: "Тапты",
    unsure: "Сенімсіз",
  },
  pilotLabel: "AI Pilot, көмекші",
  sections: {
    colors: "Түстер",
    typography: "Типографика",
    icons: "Белгішелер",
    buttons: "Түймелер",
    fields: "Енгізу өрістері",
    choice: "Таңдау",
    marks: "Белгілер",
    feedback: "Хабарламалар мен күйлер",
    list: "Тізім жолдары",
    code: "Код және QR",
    tabs: "Төменгі қойындылар",
  },
  sample: "Қозғалтқыш майы 5W-30, толық синтетикалық, 4 литр — Өнімді таңдаңыз",
  back: "Артқа",
  close: "Жабу",
  search: "Іздеу",
  clear: "Тазалау",
  primary: "Өтінім жіберу",
  secondary: "Рәсімдеу",
  cancelOrder: "Өтінімнен бас тарту",
  textButton: "Сүзгілерді тазалау",
  danger: "Аккаунтты жою",
  disabled: "Қолжетімсіз",
  pressGuard: "Әрекет орындалып жатқанда қайта басу іске қосылмайды:",
  slowAction: "2 секундтық әрекет, басулар",
  longButton: "Мерзімді растап, сатып алушыға тапсырыстың беруге дайын екенін хабарлау",
  fieldName: "Сізге қалай жүгінейік",
  fieldHint: "Жеткізуші өтінімде көреді",
  placeholder: "Мысалы, Айжан",
  fieldPhone: "Телефон нөмірі",
  fieldError: "Нөмірде +7-ден кейін 10 цифр болуы керек",
  fieldDisabled: "Қала",
  disabledValue: "Астана",
  recognized: "танылды",
  proposed: "ЖИ ұсынды",
  aiHint: "Тексеріп, растаңыз",
  aiConfirmedHint: "Расталды",
  confirm: "Растау",
  searchValue: "май 5W-30",
  searchPlaceholder: "Тауар, артикул немесе қызмет",
  codeLabel: "Өтінім коды",
  codeError: "Мұндай кодпен өтінім табылмады",
  erase: "Өшіру",
  find: "Табу",
  chips: ["Қоймада бар", "Менің көлігіме сәйкес", "Бүгін жеткізу"],
  sort: "Сұрыптау",
  segments: ["Ұсынылатын", "Арзанырақ", "Жылдамырақ"],
  switchLabel: "Өтінімдер туралы хабарламалар",
  switchDescription: "Мәртебе, беруге дайындық",
  checkboxLabel: "Клуб шарттарымен келісемін",
  pickup: "Өзі алып кету",
  courier: "Жеткізу",
  courierDescription: "Құны жеткізушімен келісіледі",
  quantity: "Саны",
  decrease: "Азайту",
  increase: "Көбейту",
  status: {
    waiting: "Құрылды",
    needsReply: "Басқа мерзім ұсынылды",
    inProgress: "Қабылданды",
    ready: "Алып кетуге болады",
    finished: "Мерзімі өтті",
  },
  compatibility: {
    fits: "Geely Monjaro көлігіне сәйкес келеді",
    missingParameter: "Қозғалтқыш көлемін нақтылаңыз",
    doesNotFit: "Geely Monjaro көлігіне сәйкес келмейді",
    unknown: "Үйлесімділігі көрсетілмеген",
  },
  ratingLabel: "Рейтинг 5-тен 4,8, 23 баға",
  noRating: "Әзірге бағалар жоқ",
  offline: "Желі жоқ. Бұрын сақталған деректер көрсетілген.",
  paymentProblem: "Жазылымды ұзарту мүмкін болмады. Төлем тәсілін жаңартыңыз.",
  bannerError: "Фото жүктелмеді. Қайталап көріңіз.",
  copyCode: "Кодты көшіру",
  copied: "Код көшірілді",
  openSheet: "Төменгі панельді ашу",
  loading: "Жүктелуде",
  emptyTitle: "Әзірге өтінімдер жоқ",
  emptyText: "Каталогтан тауар тауып, клубтық бағамен өтінім рәсімдеңіз.",
  resetFilters: "Сүзгілерді тазалау",
  errorTitle: "Жүктеу мүмкін болмады",
  errorText: "Байланысты тексеріп, қайталап көріңіз.",
  retry: "Қайталау",
  codeTitle: "Алуға арналған код",
  qrLabel: "Өтінімнің QR-коды",
  codePending: "Жеткізуші өтінімді қабылдағанда код пайда болады",
  tabsFour:
    "B–C кезеңдері: AI Pilot-сыз төрт қойынды. Экранның төменгі жағында — AI Pilot бар соңғы түрі.",
  sheetTitle: "Алу тәсілі",
  sheetText: "Панель төмен сырғытқанда және күңгірт аймақты басқанда жабылады.",
  apply: "Қолдану",
  dialogTitle: "Өтінімнен бас тартасыз ба?",
  dialogText: "Жеткізушіге хабарлама жіберіледі. Өтінімді қалпына келтіру мүмкін болмайды.",
  keepOrder: "Бас тартпау",
  tabs: { catalog: "Каталог", orders: "Өтінімдер", garage: "Гараж", profile: "Профиль" },
};

export const showcaseTexts: Record<ShowcaseLang, ShowcaseTexts> = { ru, kk };
